-- local root_markers = {
--   ".eslintrc",
--   ".eslintrc.js",
--   ".eslintrc.cjs",
--   ".eslintrc.yaml",
--   ".eslintrc.yml",
--   ".eslintrc.json",
--   "eslint.config.js",
--   "eslint.config.mjs",
--   "eslint.config.cjs",
--   "eslint.config.ts",
--   "eslint.config.mts",
--   "eslint.config.cts",
--   "package.json",
-- }

-- return {
--   cmd = { "vscode-eslint-language-server", "--stdio" },
--   filetypes = {
--     "javascript",
--     "javascriptreact",
--     "javascript.jsx",
--     "typescript",
--     "typescriptreact",
--     "typescript.tsx",
--   },
--   root_markers = root_markers,
--   single_file_support = false,
--   root_dir = function(bufnr, on_dir)
--     local bufname = vim.api.nvim_buf_get_name(bufnr)
--     if bufname == "" then
--       return
--     end

--     local root = vim.fs.root(bufname, root_markers)
--     if root then
--       on_dir(root)
--     end
--   end,
--   settings = {
--     validate = "on",
--     packageManager = nil, -- auto-detect
--     useESLintClass = false,
--     experimental = {
--       useFlatConfig = false, -- will auto-detect flat config
--     },
--     codeActionOnSave = {
--       enable = false,
--       mode = "all",
--     },
--     format = true,
--     quiet = false,
--     onIgnoredFiles = "off",
--     rulesCustomizations = {},
--     run = "onType",
--     problems = {
--       shortenToSingleLine = false,
--     },
--     nodePath = nil, -- use default
--     workingDirectories = { mode = "auto" },
--     codeAction = {
--       disableRuleComment = {
--         enable = true,
--         location = "separateLine",
--       },
--       showDocumentation = {
--         enable = true,
--       },
--     },
--   },
-- }
return {}