require("bootstrap")
require("user/settings")
require("user/plugins")
require("user/theme")
require("user/lsp")
require("user/keymaps")
require("user/autocmd")
require("user/highlight")
require("user/cmp")

